cloud:
  aws:
    credentials:
      access-key: AKIAXVE4JJYY4XYLUFXO
      secret-key: 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

    region:
      static: eu-north-1
    stack:
      auto: false

application:
  bucket:
    name: e-aarogyabucket


#spring:
#  servlet:
#    multipart:
#      enabled: true
#      file-size-threshold: 2MB
#      max-file-size: 5MB
#      max-request-size: 10MB

server:
  port: 9090
